// Generated by CoffeeScript 1.12.7
(function() {
  var path;

  path = require('path');

  module.exports = {
    development: {
      basicAuth: {
        username: "dev",
        password: "123"
      }
    },
    test: {
      basicAuth: {
        username: "test",
        password: "123"
      }
    },
    production: {
      basicAuth: {
        username: "production",
        password: "123"
      }
    }
  };

}).call(this);
